/* Eduardo Leonel Navarro Avila
 * 4-I T/V CBTis-246
 * 10/03/2026+/


/*EJERCICIO 1 CARRITO DE COMPRAS*/

CREATE TABLE ARTICULO_A(
	ARTICULO_1 VARCHAR(50) NOT NULL,
	PRIMARY KEY(ARTICULO_1)
);

CREATE TABLE ARTICULO_B(
	ARTICULO_2 VARCHAR(50) NOT NULL,
	PRIMARY KEY(ARTICULO_2)
);

INSERT INTO ARTICULO_A (ARTICULO_1)
VALUES
	('AZUCAR'),
	('PAN'),
	('JUGO'),
	('REFRESCO'),
	('HARINA');

INSERT INTO ARTICULO_B (ARTICULO_2)
VALUES
	('AZUCAR'),
	('PAN'),
	('MANTEQUILLA'),
	('QUESO'),
	('MANZANA');

SELECT * FROM ARTICULO_A 
LEFT JOIN ARTICULO_B ON ARTICULO_A.ARTICULO_1 = ARTICULO_B.ARTICULO_2
UNION
SELECT * FROM ARTICULO_A 
RIGHT JOIN ARTICULO_B ON ARTICULO_A.ARTICULO_1 = ARTICULO_B.ARTICULO_2;

/*EJERCICIO 2 GERENTES Y EMPLEADOS*/

CREATE TABLE GERENTES_Y_EMPLEADOS(
	ID_EMPLEADO INT NOT NULL,
	ID_GERENTE INT NOT NULL,
	PUESTO INT NOT NULL,
	PRIMARY KEY(ID_EMPLEADO, ID_GERENTE)
);

ALTER TABLE GERENTES_Y_EMPLEADOS
DROP COLUMN PUESTO;

ALTER TABLE GERENTES_Y_EMPLEADOS
ADD COLUMN PUESTO VARCHAR(50) NOT NULL;

INSERT INTO GERENTES_Y_EMPLEADOS(ID_EMPLEADO, ID_GERENTE, PUESTO)
VALUES
	(1001,0,'PRESIDENTE'),
	(2002,1001,'DIRECTOR'),
	(3003,1001,'GERENTE'),
	(4004,2002,'INGENIERO'),
	(5005,2002,'CONTADOR'),
	(6006,2002,'ADMINISTRADOR');

ALTER TABLE GERENTES_Y_EMPLEADOS
ADD COLUMN NIVEL INT NOT NULL;

WITH RECURSIVE Organigrama AS (
    SELECT ID_EMPLEADO, ID_GERENTE, PUESTO, 0 AS NIVEL
    FROM GERENTES_Y_EMPLEADOS
    WHERE ID_GERENTE = 0
    UNION ALL
    SELECT e.Id_empleado, e.Id_gerente, e.Puesto, o.Nivel + 1
    FROM GERENTES_Y_EMPLEADOS e
    INNER JOIN Organigrama o ON e.Id_gerente = o.Id_empleado
)
SELECT * FROM Organigrama;

/*EJERCICIO 3 DOS PREDICADOS*/

CREATE TABLE ENTREGAS(
	ID_CLIENTE INT NOT NULL,
	ID_ORDEN INT  NOT NULL,
	ESTADO_DESTINO VARCHAR(100) NOT NULL,
	COSTO DOUBLE NOT NULL,
	PRIMARY KEY (ID_CLIENTE, ID_ORDEN)
);

INSERT INTO ENTREGAS(ID_CLIENTE, ID_ORDEN, ESTADO_DESTINO, COSTO)
VALUES
	(1001,1,'JAL',987),
	(1001,2,'CDMX',400),
	(1001,3,'CDMX',545),
	(1001,4,'CDMX',321),
	(2002,5,'MTY',324),
	(3003,6,'JAL',931),
	(4004,7,'JAL',876),
	(5005,8,'CDMX',567);

SELECT Id_cliente, Id_Orden, Estado_Destino, Costo
FROM ENTREGAS
WHERE Estado_Destino = 'CDMX'
AND Id_cliente IN (
    SELECT Id_cliente 
    FROM ENTREGAS 
    WHERE Estado_Destino = 'JAL'
);
