/* Eduardo Leonel Navarro Avila
 * 4-I T/V CBTis-246
 * 13/03/2026*/

/*-ACTIVIDAD 1-
 * PERMUTACIONES
 */

/*NOTA PEROSNAL:
 * PARTE 1: COMO SE ILUSTRARA EN EL RESULTADO FINAL CON: AS PRIMERO, SEGUNDO, TERCERO
 * PARTE 2: REPITE LA TABLA 3 VECES PA QUE EL PROGRAMA NO EXPLOTE CON: AS t1, 2 y 3
 * PARTE 3. PARA QUE NO SE REPITA LETRA "<>" ES COMO UN IGUALN'T
 */

CREATE TABLE CASO_P(
CASO VARCHAR(10) NOT NULL,
PRIMARY KEY (CASO)
);

INSERT INTO CASO_P(CASO)
VALUES
	('A'),
	('B'),
	('C');

SELECT 
    t1.CASO AS Primero, 
    t2.CASO AS Segundo, 
    t3.CASO AS Tercero
FROM CASO_P AS t1
CROSS JOIN CASO_P AS t2
CROSS JOIN CASO_P AS t3
WHERE t1.CASO <> t2.CASO
  AND t1.CASO <> t3.CASO
  AND t2.CASO <> t3.CASO;

/*-ACTIVIDAD 2-
 * PROMEDIO DE DÍAS
 */

/*NOTA PERSONAL:
 * PARTE 1: DATEDIFF RESTA LAS FECHAS QUE QUIERAS RESTAR
 * PARTE 2: LA PARTE DE LEAD HACE QUE LA TABLA RESTE EL NUMERO CON EL DE ABAJO SOLO SI TIENEN EL MISMO VALOR EN LA COLUMNA 'DDESARROLLO'
 * PARTE 3: WITH 'DIFERENCE' CREA UNA TABLA TEMPORAL EN LO QUE SACAMOS EL PROMEDIO
 * PARTE 4: AVG CALCULA EL PROMEDIO
 */

CREATE TABLE PROMEDIO(
	DESARROLLO VARCHAR(50) NOT NULL,
	TERMINADO DATE NOT NULL,
	PRIMARY KEY(DESARROLLO, TERMINADO)
);

INSERT INTO PROMEDIO (DESARROLLO, TERMINADO)
VALUES
	('RestAPI', '2024-06-01'),
    ('RestAPI', '2024-06-14'),
    ('RestAPI', '2024-06-15'),
    ('Web', '2024-06-01'),
    ('Web', '2024-06-02'),
    ('Web', '2024-06-19'),
    ('App', '2024-06-01'),
    ('App', '2024-05-15'),
    ('App', '2024-06-30');

WITH Diferencias AS (
    SELECT 
        DESARROLLO,
        TERMINADO,
        DATEDIFF(
            LEAD(TERMINADO) OVER (PARTITION BY DESARROLLO ORDER BY TERMINADO), 
            TERMINADO
        ) AS dias_diferencia
    FROM PROMEDIO
)
SELECT 
    DESARROLLO, 
    AVG(dias_diferencia) AS promedio_dias
FROM Diferencias
WHERE dias_diferencia IS NOT NULL
GROUP BY DESARROLLO;

/*-ACTIVIDAD 3-
 * SEGUIMIENTO DE INVENTARIO
 */

/*NOTA PERSONAL:
 * PARTE 1: SUM('COLUMNA') ES PARA VER EN QUE COLUMNA SUMAR
 * PARTE 2: 'OVER' ES PARA QUE LO HAGA EN ORDEN
 * PARTE 3: (ORDER BY 'COLUMNA') ES PARA INDICAR EL ORDEN, EN ESTE CASO LA OTRA COLUMNA
 * PARTE 4: 'AS 'INVENTARIO' INDICA EL NOMBRE UQE TENDRA LA COLUMNA DE RESULTADO
 */

CREATE TABLE SEGUIMIENTO(
	FECHA DATE NOT NULL,
	AJUSTE INT NOT NULL,
	PRIMARY KEY (FECHA, AJUSTE)
);

INSERT INTO SEGUIMIENTO(FECHA, AJUSTE)
VALUES
	('2025-01-03', 100),
    ('2025-01-04', 75),
    ('2025-01-05', -150),
    ('2025-01-06', 50),
    ('2025-01-07', -70);

SELECT 
    FECHA, 
    AJUSTE,
    SUM(AJUSTE) OVER (ORDER BY FECHA) AS INVENTARIO
FROM SEGUIMIENTO;
